# Generated by Django 5.1 on 2024-08-18 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestMyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField()),
                ('datetime_updated', models.DateTimeField(blank=True, null=True)),
                ('field1', models.CharField(max_length=20)),
                ('field2', models.CharField(max_length=20)),
                ('user_created', models.IntegerField()),
                ('ip_created', models.CharField(max_length=15)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('record_uuid', models.UUIDField(unique=True)),
                ('ip_updated', models.CharField(blank=True, max_length=15, null=True)),
                ('user_updated', models.IntegerField(blank=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
